const tasks = [
  {
    id: 1,
    title: 'Write a report',
    isCompleted: false,
    details: 'Some details of the task',
    remarks: 'Some Remarks of the task',
    isImportant: false,
  },
  {
    id: 2,
    title: 'Review project documentation',
    isCompleted: true,
    details: 'Some details of the task',
    remarks: 'Some Remarks of the task',
    isImportant: true,
  },
  {
    id: 3,
    title: 'Code review with team',
    isCompleted: false,
    details: 'Some details of the task',
    remarks: 'Some Remarks of the task',
    isImportant: true,
  },
  {
    id: 4,
    title: 'Lunch break',
    isCompleted: false,
    details: 'Some details of the task',
    remarks: 'Some Remarks of the task',
    isImportant: false,
  },
  {
    id: 5,
    title: 'Client meeting',
    isCompleted: true,
    details: 'Some details of the task',
    remarks: 'Some Remarks of the task',
    isImportant: true,
  },
  {
    id: 6,
    title: 'Research new technologies',
    isCompleted: true,
    details: 'Some details of the task',
    remarks: 'Some Remarks of the task',
    isImportant: false,
  },
  {
    id: 7,
    title: 'Exercise',
    isCompleted: false,
    details: 'Some details of the task',
    remarks: 'Some Remarks of the task',
    isImportant: false,
  },
  {
    id: 8,
    title: 'Read a book',
    isCompleted: true,
    details: 'Some details of the task',
    remarks: 'Some Remarks of the task',
    isImportant: false,
  },
  {
    id: 9,
    title: 'Dinner',
    isCompleted: false,
    details: 'Some details of the task',
    remarks: 'Some Remarks of the task',
    isImportant: true,
  },
  {
    id: 10,
    title: 'Plan for tomorrow',
    isCompleted: true,
    details: 'Some details of the task',
    remarks: 'Some Remarks of the task',
    isImportant: true,
  },
];

export default tasks;
